name: Ping Strapi

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  ping:
    name: A job to ping
    runs-on: ubuntu-latest
    env:
      URL: www.thomassjerps.nl/api/jh-portfolio-tags?locale=en
      METHOD: GET
    steps:
      - id: ping
        uses: sisodiya2421/pinger@master